environment:
    nodejs_version: "5.8.0"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm rm -g gulp
  - npm install -g gulp-cli
  - npm install
  - set NODE_ENV=production

build_script:
  - npm test
  - gulp build
